esphome:
  name: "apator-reader"
  platform: ESP8266
  board: nodemcuv2
     
  includes:
    - custom_components/apator.h

  libraries:
    -  SPI
    - "https://github.com/bblanchon/ArduinoJson.git"
    - "https://github.com/LSatan/SmartRC-CC1101-Driver-Lib.git"
    - "https://github.com/SzczepanLeon/wMbus-lib.git"
    - "https://github.com/MariuszWoszczynski/Apator-meter-reader-core.git"

# Enable logging
logger: 
  level: DEBUG

# Enable Home Assistant API
api:
  encryption:
    key: "****************************************"

ota:
  password: "****************************************"

wifi:
  ssid: "****************************************"
  password: "****************************************"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "****************************************"
    password: "****************************************"

captive_portal:


sensor:
  - platform: custom
    lambda: |-
      auto sensor = new MySensor();
      App.register_component(sensor);
      return {sensor->Apator_state_1, sensor->Apator_id_1, sensor->Apator_state_2, sensor->Apator_id_2};
    sensors:
      - name: Stan licznika wody Apator 1
        unit_of_measurement: L
        accuracy_decimals: 0
      - name: Id licznika wody Apator 1
        accuracy_decimals: 0
      - name: Stan licznika wody Apator 2
        unit_of_measurement: L
        accuracy_decimals: 0
      - name: Id licznika wody Apator 2
        accuracy_decimals: 0

