esphome:
  name: "apator-reader"
  platform: ESP8266
  board: nodemcuv2
     
  includes:
    - custom_components/apator.h

  libraries:
    -  SPI
    - "https://github.com/bblanchon/ArduinoJson.git"
    - "https://github.com/LSatan/SmartRC-CC1101-Driver-Lib.git"
    - "https://github.com/SzczepanLeon/wMbus-lib.git"
    - "https://github.com/MariuszWoszczynski/Apator-meter-reader-core.git"

# Enable logging
logger: 
  level: DEBUG

# Enable Home Assistant API
api:
  encryption:
    key: "****************************************"

ota:
  password: "****************************************"

wifi:
  ssid: "****************************************"
  password: "****************************************"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "****************************************"
    password: "****************************************"

captive_portal:

text_sensor:
  - platform: custom
    lambda: |-
      auto textsensor = new MyTextSensor();
      App.register_component(textsensor);
      return {textsensor->Apator_ID_1, textsensor->Apator_ID_2};
    text_sensors:
      - name: Meter 1 ID                    #text 
        filters:
        - to_upper:
      - name: Meter 2 ID                    #text 
        filters:
        - to_upper:

sensor:
  - platform: custom
    lambda: |-
      auto sensor = new MySensor();
      App.register_component(sensor);
      return {sensor->Apator_state_1, sensor->Apator_state_2};
    sensors:
      - name: Water meter 1 state          #float value
        unit_of_measurement: L
        accuracy_decimals: 0
      - name: Water meter 2 state          #float value
        unit_of_measurement: L
        accuracy_decimals: 0
